### ISSUE TITLE
Should not hide exceptions

### ISSUE THREAD

**Issue by vojtajina** [yaymukund/grunt-simple-mocha#19]
directly with mocha:
````
$ mocha --compilers coffee:coffee-script test/mocha-common.js test/unit/*

  ․․․․․․․․․․․․  ✖ 1 of 12 tests failed:

  1) web-server testacular source handler should serve client.html:
     TypeError: null is not a spy or a call to a spy!
      at assertCanWorkWith (/Users/vojta/Code/testacular/node_modules/sinon-chai/lib/sinon-chai.js:35:19)
      at Assertion.alwaysSinonMethod (/Users/vojta/Code/testacular/node_modules/sinon-chai/lib/sinon-chai.js:58:13)
      at Assertion.Object.defineProperty.get (/Users/vojta/Code/testacular/node_modules/chai/lib/chai/utils/addProperty.js:35:29)
      at MockHTTPResponse.includedFiles.path (/Users/vojta/Code/testacular/test/unit/web-server.spec.coffee:164:43)
      at MockHTTPResponse.g (events.js:185:14)
      at MockHTTPResponse.EventEmitter.emit (events.js:85:17)
      at MockHTTPResponse.end (/Users/vojta/Code/testacular/node_modules/mock-http-response/src/index.coffee:80:19)
      at /Users/vojta/Code/testacular/lib/web-server.js:40:21
      at Array.Mock.readFile (/Users/vojta/Code/testacular/node_modules/mocks/lib/fs.js:195:7)
      at nextTickHandler (/Users/vojta/Code/testacular/node_modules/mocks/lib/util.js:29:31)
      at process.startup.processNextTick.process._tickCallback (node.js:244:9)
````

through simple-mocha:
````
grunt simplemocha:unit
Running "simplemocha:unit" (simplemocha) task

  ․․․․․․․․․․․Fatal error: null is not a spy or a call to a spy!
````

**Comment by yaymukund** [comment]
This is an ancient issue, but you should be able to pass in `fullTrace: true` as an option. Please reopen if I'm misunderstanding the issue or if that doesn't work. Thank you for reporting.
